extends TestCase
## Covers core/serialization/save_version.gd (brick 017).


func _header(overrides: Dictionary = {}) -> Dictionary:
	var header := SaveVersion.make_header(12345)
	for key in overrides:
		header[key] = overrides[key]
	return header


func test_header_carries_the_four_independent_numbers() -> void:
	var header := SaveVersion.make_header(999)
	assert_eq(int(header["world_format_version"]), SaveVersion.WORLD_FORMAT_VERSION)
	assert_eq(int(header["generation_version"]), SaveVersion.GENERATION_VERSION)
	assert_eq(int(header["data_version"]), SaveVersion.DATA_VERSION)
	assert_eq(int(header["seed"]), 999, "the seed identifies the world")


func test_header_diagnostics_are_present_but_not_required() -> void:
	var header := SaveVersion.make_header(1)
	assert_has(header, "engine_version")
	assert_has(header, "saved_at_unix")
	# Nothing may branch on them, so they are not in the required set: a save missing
	# them still loads.
	assert_false(SaveVersion.REQUIRED_FIELDS.has("saved_at_unix"),
			"the wall clock is never load-bearing")


func test_extra_fields_are_carried_through() -> void:
	var header := SaveVersion.make_header(1, {"world_name": "test"})
	assert_eq(header["world_name"], "test")


func test_a_fresh_header_is_current() -> void:
	assert_eq(SaveVersion.classify(_header()), SaveVersion.Compatibility.CURRENT)
	assert_true(SaveVersion.can_load(_header()))


func test_a_newer_save_is_refused() -> void:
	# This build cannot know what a future build added. Guessing corrupts the save.
	var header := _header({"world_format_version": SaveVersion.WORLD_FORMAT_VERSION + 1})
	assert_eq(SaveVersion.classify(header), SaveVersion.Compatibility.TOO_NEW)
	assert_false(SaveVersion.can_load(header))
	assert_has(SaveVersion.explain(header), "newer build")


func test_a_save_below_the_supported_floor_is_refused() -> void:
	# With the floor still at format 1, the only value below it is 0, which the
	# structural check rejects first — so the refusal is MALFORMED, not TOO_OLD. Both
	# refuse; this pins which reason a player is given today. TOO_OLD becomes reachable
	# the first time MIN_SUPPORTED_FORMAT_VERSION is raised above 1.
	assert_eq(SaveVersion.MIN_SUPPORTED_FORMAT_VERSION, 1,
			"this test describes the floor as it stands")
	var header := _header({"world_format_version": 0})
	assert_eq(SaveVersion.classify(header), SaveVersion.Compatibility.MALFORMED)
	assert_false(SaveVersion.can_load(header), "either way, it does not load")


func test_the_supported_range_is_coherent() -> void:
	assert_true(SaveVersion.MIN_SUPPORTED_FORMAT_VERSION <= SaveVersion.WORLD_FORMAT_VERSION,
			"the build cannot require a format newer than the one it writes")
	assert_true(SaveVersion.MIN_SUPPORTED_GENERATION_VERSION <= SaveVersion.GENERATION_VERSION)


func test_a_missing_generator_blocks_loading() -> void:
	# The container parses, but unexplored terrain would not match what is already
	# stored — a world half-generated by two different algorithms.
	var header := _header({"generation_version": 7})
	assert_eq(SaveVersion.classify(header), SaveVersion.Compatibility.GENERATOR_UNAVAILABLE)
	assert_false(SaveVersion.can_load(header))
	assert_has(SaveVersion.explain(header), "no longer implements")


func test_an_available_older_generator_still_loads() -> void:
	# A build that keeps an old generator around can open the world and keep generating
	# with the algorithm it was created with.
	var header := _header({"generation_version": 1})
	assert_true(SaveVersion.can_load(header, PackedInt32Array([1, 2])))


func test_a_generator_absent_from_the_available_list_is_refused() -> void:
	var header := _header({"generation_version": 2})
	assert_eq(SaveVersion.classify(header, PackedInt32Array([1])),
			SaveVersion.Compatibility.GENERATOR_UNAVAILABLE)


func test_malformed_headers_are_reported_not_guessed() -> void:
	assert_eq(SaveVersion.classify({}), SaveVersion.Compatibility.MALFORMED)

	var missing := _header()
	missing.erase("seed")
	assert_eq(SaveVersion.classify(missing), SaveVersion.Compatibility.MALFORMED)
	assert_has(SaveVersion.validate_header(missing), "seed")

	var wrong_type := _header({"world_format_version": "1"})
	assert_eq(SaveVersion.classify(wrong_type), SaveVersion.Compatibility.MALFORMED)
	assert_has(SaveVersion.validate_header(wrong_type), "integer")

	var zero := _header({"world_format_version": 0})
	assert_has(SaveVersion.validate_header(zero), "positive")


func test_validate_accepts_a_good_header() -> void:
	assert_eq(SaveVersion.validate_header(_header()), "")


func test_migration_steps_are_ordered_and_empty_when_current() -> void:
	assert_eq(SaveVersion.migration_steps(SaveVersion.WORLD_FORMAT_VERSION),
			PackedInt32Array(), "a current save migrates nothing")
	assert_eq(SaveVersion.migration_steps(SaveVersion.WORLD_FORMAT_VERSION + 5),
			PackedInt32Array(), "a newer save is not migrated backwards")

	# Simulated: a save two versions behind runs both steps, in order.
	var steps := SaveVersion.migration_steps(SaveVersion.WORLD_FORMAT_VERSION - 2)
	assert_size(steps, 2)
	assert_eq(steps[0], SaveVersion.WORLD_FORMAT_VERSION - 1)
	assert_eq(steps[1], SaveVersion.WORLD_FORMAT_VERSION)


func test_data_version_drift_is_detected_but_not_fatal() -> void:
	# Content growing is normal; it must not read as a broken save.
	var header := _header({"data_version": SaveVersion.DATA_VERSION + 1})
	assert_true(SaveVersion.data_version_differs(header))
	assert_true(SaveVersion.can_load(header), "content drift still loads")
	assert_false(SaveVersion.data_version_differs(_header()))


func test_the_version_numbers_are_independent() -> void:
	# The point of keeping four numbers: adding a block must not invalidate saves, and
	# changing the generator must be distinguishable from it.
	var content_only := _header({"data_version": SaveVersion.DATA_VERSION + 1})
	assert_eq(SaveVersion.classify(content_only), SaveVersion.Compatibility.CURRENT,
			"a content change alone does not touch load compatibility")

	var generator_only := _header({"generation_version": 99})
	assert_eq(SaveVersion.classify(generator_only),
			SaveVersion.Compatibility.GENERATOR_UNAVAILABLE,
			"a generator change is caught even though the container is fine")


func test_explain_always_says_something_useful() -> void:
	# A player told only "cannot load" deletes the save.
	for header in [_header(), _header({"world_format_version": 99}),
			_header({"generation_version": 99}), {}]:
		assert_true(SaveVersion.explain(header).length() > 10,
				"every verdict explains itself")
